#!/usr/bin/env node
/**
 * Forge RTM builder — Phase 5.
 *
 * Assembles a Requirements Traceability Matrix from every work order's artifacts
 * + `.forge` state (JIRA / SonarQube / Confluence) and writes
 * `openspec/forge/rtm.md`. One row per requirement:
 *   Work Order -> Requirement -> Control(s) -> JIRA -> Confluence -> Sonar -> Branch.
 *
 * Usage: node openspec/forge/build-rtm.mjs [--root <path>]
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { readJiraState } from './lib/jira.mjs';
import { readSonarResult } from './lib/sonar.mjs';
import { readConfluenceState } from './lib/confluence.mjs';

function parseArgs(argv) {
  const a = { root: process.cwd() };
  for (let i = 2; i < argv.length; i++) {
    const x = argv[i];
    if (x === '--root') a.root = path.resolve(argv[++i]);
    else if (x === '-h' || x === '--help') a.help = true;
  }
  return a;
}
function listMd(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...listMd(f));
    else if (e.name.endsWith('.md')) out.push(f);
  }
  return out;
}
function schemaOf(changeDir) {
  const p = path.join(changeDir, '.openspec.yaml');
  if (!existsSync(p)) return null;
  const m = readFileSync(p, 'utf8').match(/^schema:\s*(.+)$/m);
  return m ? m[1].trim() : null;
}
function requirementsOf(changeDir) {
  const reqs = [];
  for (const f of listMd(path.join(changeDir, 'specs'))) {
    const c = readFileSync(f, 'utf8');
    const re = /^###\s+Requirement:\s*(.+)$/gm;
    let m;
    while ((m = re.exec(c))) {
      const name = m[1].trim();
      const window = c.slice(m.index, m.index + 500);
      const controls = [...window.matchAll(/\(control:\s*([^)]+)\)/g)]
        .flatMap((x) => x[1].split(/[,\s]+/))
        .map((s) => s.trim())
        .filter(Boolean);
      reqs.push({ name, controls: [...new Set(controls)] });
    }
  }
  return reqs;
}
const esc = (s) => String(s).replace(/\|/g, '\\|');

function main() {
  const a = parseArgs(process.argv);
  if (a.help) { console.log('Usage: node openspec/forge/build-rtm.mjs [--root <path>]'); process.exit(0); }
  const root = a.root;
  const changesDir = path.join(root, 'openspec', 'changes');
  const rows = [];
  if (existsSync(changesDir)) {
    for (const e of readdirSync(changesDir, { withFileTypes: true }).sort((x, y) => x.name.localeCompare(y.name))) {
      if (!e.isDirectory() || e.name === 'archive') continue;
      const cd = path.join(changesDir, e.name);
      if (schemaOf(cd) !== 'forge-workorder') continue;
      const jira = readJiraState(cd);
      const sonar = readSonarResult(cd);
      const conf = readConfluenceState(cd);
      const jiraCell = jira?.key ? `[${jira.key}](${jira.url || '#'})${jira.status ? ` (${jira.status})` : ''}` : '—';
      const confCell = conf ? (conf.approved ? 'approved' : 'pending') : '—';
      const sonarCell = sonar ? sonar.status : '—';
      const branchCell = `forge/${jira?.key || e.name}`;
      const reqs = requirementsOf(cd);
      if (reqs.length === 0) rows.push([e.name, '—', '—', jiraCell, confCell, sonarCell, branchCell]);
      for (const r of reqs) rows.push([e.name, r.name, r.controls.join(', ') || '—', jiraCell, confCell, sonarCell, branchCell]);
    }
  }
  const header = ['Work Order', 'Requirement', 'Controls', 'JIRA', 'Confluence', 'Sonar', 'Branch'];
  const md = [
    '# Requirements Traceability Matrix',
    '',
    `_Generated by \`forge rtm\` on ${new Date().toISOString()}. Do not edit by hand._`,
    '',
    `| ${header.join(' | ')} |`,
    `| ${header.map(() => '---').join(' | ')} |`,
    ...rows.map((r) => `| ${r.map(esc).join(' | ')} |`),
    '',
  ].join('\n');
  const out = path.join(root, 'openspec', 'forge', 'rtm.md');
  writeFileSync(out, md);
  console.log(`Wrote ${out}   (${rows.length} row(s))`);
}

main();
